spring:
  application:
    name: shopping-cart

  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5433/sht"  #5432
    username: "sh"
    password: "sh"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true

    sql:
      init:
        mode: always

server:
  port: 0

logging:
  level:
    ru.yandex.practicum: DEBUG