spring:
  application:
    name: warehouse

  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5433/sht?currentSchema=warehouse"  #5432
    username: "sh"
    password: "sh"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true

  sql:
    init:
      mode: always

server:
  port: 0

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.hibernate.tool.schema: DEBUG