spring:
  application:
    name: collector

collector:
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: INFO

