spring:
  application:
    name: analyzer

  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5433/sht"  #5432
    username: "sh"
    password: "sh"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true

  sql:
    init:
      mode: always

analyzer:
  kafka:
    bootstrap-servers: localhost:9092

    consumers:
      snapshot:
        bootstrap-servers: ${analyzer.kafka.bootstrap-servers}
        group-id: telemetry.analyzer.snapshot
        auto-offset-reset: earliest
        consume-attempt-timeout-ms: 1000
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: ru.yandex.practicum.kafka.deserializer.SensorsSnapshotDeserializer
      hubs:
        bootstrap-servers: ${analyzer.kafka.bootstrap-servers}
        group-id: telemetry.analyzer.hub
        auto-offset-reset: earliest
        consume-attempt-timeout-ms: 7000
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
    topics:
      snapshots:
        - telemetry.snapshots.v1
      hubs:
        - telemetry.hubs.v1

  grpc:
    server:
      port: 59092
    client:
      hub-router:
        address: 'discovery:///hub-router' #'static://localhost:59090'
        enableKeepAlive: true
        keepAliveWithoutCalls: true
        negotiationType: plaintext

logging:
  level:
    ru.yandex.practicum: DEBUG

