spring:
  application:
    name: shopping-store

  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5433/sht?currentSchema=store"  #5432
    username: "sh"
    password: "sh"

  jpa:
    hibernate:
      ddl-auto: validate
#    open-in-view: false  # Prevents lazy initialization exceptions but requires careful handling of transactions.
    show-sql: true # Useful for debugging SQL queries.
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true

  sql:
    init:
      mode: always

server:
  port: 0

logging:
  level:
    ru.yandex.practicum: DEBUG
